### ISSUE TITLE
Documentation for RenderTexture incomplete

### ISSUE THREAD

**Issue by wolfgang371** [oprypin/crystal-imgui-sfml#2]
SFML seems to have a problem with `RenderTexture`s in combination with `Sprite`s. Typically, the sprites will get drawn upside down.

This also took me a while, but finally I came across https://stackoverflow.com/questions/22424124/sfml-rendertexture-flipped-output, which helped me solve the problem easily.

Maybe you want to update your code example accordingly in https://oprypin.github.io/crsfml/api/SF/RenderTexture.html.

```crystal
frame = SF::Image.from_file("some.jpg")
texture = SF::RenderTexture.new(frame.size.x, frame.size.y)
texture.draw(SF::Sprite.new(SF::Texture.from_image(frame))) # this will get drawn flipped except...
rectangle = SF::RectangleShape.new
rectangle.size = SF.vector2f(100, 50)
rectangle.outline_color = SF::Color::Red
rectangle.outline_thickness = 5
rectangle.position = {300, 200}
texture.draw(rectangle)
texture.display
sprite = SF::Sprite.new(texture.texture.dup) # ... you use `.dup` here!

ImGui.image_button(sprite)
```

**Comment by oprypin** [comment]
https://github.com/eliasdaler/imgui-sfml/issues/35#issuecomment-357152982 - it seems like they never ended up adding those overloads like they planned.
https://github.com/eliasdaler/imgui-sfml/search?q=RenderTexture&type=code
Maybe I can add it directly here though

**Comment by oprypin** [comment]
No, I'm not finding an appropriate way to implement this as part of imgui-sfml. They really just need to add that overload, then I'll do the same.

**Comment by wolfgang371** [comment]
I also saw those comments/promises about the overloads years ago; but obviously they didn't come. Nevertheless users have an issue with those RenderTextures. So I was searching for a workaround and the easiest I could find was the `.dup` one. But this is completely unintuitive, so I thought (for the next couple of years) users might be grateful for this hint.

**Comment by eliasdaler** [comment]
Hello, I'm sorry about the delay - the problem was pretty complex and I kinda procrastinated, yep.
Check out [this comment](https://github.com/eliasdaler/imgui-sfml/issues/35#issuecomment-782991372) which has some explanations about the possible overload.

If you check out "render-texture-fixes" branch and it'll work for you, then I'll merge it into master soon.

**Comment by oprypin** [comment]
Yes, that branch works well, thank you!

Then the example above just needs to be changed `ImGui.image_button(sprite)` &rarr; `ImGui.image_button(texture)`

**Comment by wolfgang371** [comment]
I can also confirm - thank you!

**Comment by eliasdaler** [comment]
The fix merged into master, here: https://github.com/eliasdaler/imgui-sfml/commit/ee41e16f36b21bc5556ef7dfe13e2df143f37531
Also added a note about `sf::RenderTexture` in README.
