### ISSUE TITLE
Update inquiry for v1.90.4

### ISSUE THREAD

**Issue by wolfgang371** [oprypin/crystal-imgui-sfml#4]
Hi @oprypin 
since imgui progressed again quite a bit the last 6 months, do you think you can generate a new version for https://github.com/ocornut/imgui/releases/tag/v1.90.4
Thanks! :smile:

**Comment by oprypin** [comment]
Yeah I should get back into this,

The majority of the update is about getting a corresponding release in cimgui and making sure that the demo files still work.

But should be doable in any case, I just need to remember.

**Comment by oprypin** [comment]
Done!
